<a href="https://colab.research.google.com/github/dntmdxor99/pytorch/blob/main/1_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [4]:
x_ones = torch.ones_like(x_data)
x_ones

tensor([[1, 1],
        [1, 1]])

In [7]:
x_rand = torch.rand_like(x_data, dtype = torch.float)  # 기본적으로 주어진 인자의 속성(모양, 자료형)을 공유하기 때뭉네 정의해줘야 한다.
x_rand

tensor([[0.7441, 0.9549],
        [0.8671, 0.6639]])

In [16]:
shape = (2, 3, )
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

In [17]:
rand_tensor

tensor([[0.5272, 0.6315, 0.6977],
        [0.1298, 0.2627, 0.7076]])

In [18]:
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [19]:
zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [21]:
tensor = torch.rand(3,4,)
tensor

tensor([[0.3501, 0.3139, 0.5653, 0.3036],
        [0.7919, 0.4479, 0.8858, 0.8527],
        [0.9666, 0.2646, 0.1120, 0.0919]])

In [22]:
tensor.device

device(type='cpu')

In [23]:
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [24]:
tensor.device

device(type='cuda', index=0)

In [27]:
tensor = torch.rand(4, 4)
print(tensor)
print(tensor[..., -1])
print(tensor[:, -1])

tensor([[0.1103, 0.0831, 0.1362, 0.8736],
        [0.7939, 0.6119, 0.0823, 0.3487],
        [0.8957, 0.3732, 0.3057, 0.6541],
        [0.9062, 0.5380, 0.7129, 0.5578]])
tensor([0.8736, 0.3487, 0.6541, 0.5578])
tensor([0.8736, 0.3487, 0.6541, 0.5578])


In [28]:
tensor[:, 1] = 0
tensor

tensor([[0.1103, 0.0000, 0.1362, 0.8736],
        [0.7939, 0.0000, 0.0823, 0.3487],
        [0.8957, 0.0000, 0.3057, 0.6541],
        [0.9062, 0.0000, 0.7129, 0.5578]])

In [33]:
t1 = torch.cat([tensor, tensor, tensor], dim = 0)
t1

tensor([[0.1103, 0.0000, 0.1362, 0.8736],
        [0.7939, 0.0000, 0.0823, 0.3487],
        [0.8957, 0.0000, 0.3057, 0.6541],
        [0.9062, 0.0000, 0.7129, 0.5578],
        [0.1103, 0.0000, 0.1362, 0.8736],
        [0.7939, 0.0000, 0.0823, 0.3487],
        [0.8957, 0.0000, 0.3057, 0.6541],
        [0.9062, 0.0000, 0.7129, 0.5578],
        [0.1103, 0.0000, 0.1362, 0.8736],
        [0.7939, 0.0000, 0.0823, 0.3487],
        [0.8957, 0.0000, 0.3057, 0.6541],
        [0.9062, 0.0000, 0.7129, 0.5578]])

In [34]:
t1 = torch.cat([tensor, tensor, tensor], dim = 1)
t1

tensor([[0.1103, 0.0000, 0.1362, 0.8736, 0.1103, 0.0000, 0.1362, 0.8736, 0.1103,
         0.0000, 0.1362, 0.8736],
        [0.7939, 0.0000, 0.0823, 0.3487, 0.7939, 0.0000, 0.0823, 0.3487, 0.7939,
         0.0000, 0.0823, 0.3487],
        [0.8957, 0.0000, 0.3057, 0.6541, 0.8957, 0.0000, 0.3057, 0.6541, 0.8957,
         0.0000, 0.3057, 0.6541],
        [0.9062, 0.0000, 0.7129, 0.5578, 0.9062, 0.0000, 0.7129, 0.5578, 0.9062,
         0.0000, 0.7129, 0.5578]])

In [39]:
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(y1)
print(y1)
print(y2)
print(torch.matmul(tensor, tensor.T, out = y3))

tensor([[0.7940, 0.4034, 0.7119, 0.6844],
        [0.4034, 0.7586, 0.9643, 0.9726],
        [0.7119, 0.9643, 1.3235, 1.3945],
        [0.6844, 0.9726, 1.3945, 1.6407]])
tensor([[0.7940, 0.4034, 0.7119, 0.6844],
        [0.4034, 0.7586, 0.9643, 0.9726],
        [0.7119, 0.9643, 1.3235, 1.3945],
        [0.6844, 0.9726, 1.3945, 1.6407]])
tensor([[0.7940, 0.4034, 0.7119, 0.6844],
        [0.4034, 0.7586, 0.9643, 0.9726],
        [0.7119, 0.9643, 1.3235, 1.3945],
        [0.6844, 0.9726, 1.3945, 1.6407]])


In [40]:
z1 = tensor * tensor
z2 = tensor.mul(tensor)
print(z1)
print(z2)

tensor([[0.0122, 0.0000, 0.0185, 0.7633],
        [0.6303, 0.0000, 0.0068, 0.1216],
        [0.8023, 0.0000, 0.0934, 0.4278],
        [0.8212, 0.0000, 0.5083, 0.3112]])
tensor([[0.0122, 0.0000, 0.0185, 0.7633],
        [0.6303, 0.0000, 0.0068, 0.1216],
        [0.8023, 0.0000, 0.0934, 0.4278],
        [0.8212, 0.0000, 0.5083, 0.3112]])


In [43]:
agg = tensor.sum()
agg_item = agg.item()
print(agg)
agg_item

tensor(6.3774)


6.377408504486084

In [44]:
tensor.add(5)

tensor([[5.1103, 5.0000, 5.1362, 5.8736],
        [5.7939, 5.0000, 5.0823, 5.3487],
        [5.8957, 5.0000, 5.3057, 5.6541],
        [5.9062, 5.0000, 5.7129, 5.5578]])

In [45]:
tensor

tensor([[0.1103, 0.0000, 0.1362, 0.8736],
        [0.7939, 0.0000, 0.0823, 0.3487],
        [0.8957, 0.0000, 0.3057, 0.6541],
        [0.9062, 0.0000, 0.7129, 0.5578]])

In [46]:
tensor.add_(5)
tensor

tensor([[5.1103, 5.0000, 5.1362, 5.8736],
        [5.7939, 5.0000, 5.0823, 5.3487],
        [5.8957, 5.0000, 5.3057, 5.6541],
        [5.9062, 5.0000, 5.7129, 5.5578]])

In [47]:
t = torch.ones(5)
print(t)
n = t.numpy()
print(n)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [48]:
t.add_(1)
print(t)
print(n)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [50]:
n = np.ones(5)
t = torch.from_numpy(n)
print(n)
print(t)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [52]:
np.add(n, 1, out = n)
print(t)
print(n)

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
